#include "config_manager.h"

#include <fstream>
#include <iostream>
#include <toml++/toml.hpp>

bool ConfigManager::Load(const std::filesystem::path& toml_path, GameConfig& config) {
  if (!std::filesystem::exists(toml_path)) {
    return false;
  }
  try {
    auto tbl = toml::parse_file(toml_path.string());
    if (auto v = tbl["gpu_plugin"].value<std::string>()) config.gpu_plugin = *v;
    if (auto v = tbl["d3d12_readback_resolve"].value<bool>()) config.d3d12_readback_resolve = *v;
    if (auto v = tbl["skip_intro_videos"].value<bool>()) config.skip_intro_videos = *v;
    if (auto v = tbl["log_verbose"].value<bool>()) config.log_verbose = *v;
    if (auto v = tbl["log_level"].value<std::string>()) config.log_level = *v;
    if (auto v = tbl["protect_zero"].value<bool>()) config.protect_zero = *v;
    if (auto v = tbl["input_backend"].value<std::string>()) config.input_backend = *v;
    if (auto v = tbl["mnk_mode"].value<bool>()) config.mnk_mode = *v;
    if (auto v = tbl["fullscreen"].value<bool>()) config.fullscreen = *v;
    if (auto v = tbl["vsync"].value<bool>()) config.vsync = *v;
    if (auto v = tbl["d3d12_host_vsync"].value<bool>()) config.d3d12_host_vsync = *v;
    if (auto v = tbl["video_mode_refresh_rate"].value<double>()) config.video_mode_refresh_rate = *v;
    if (auto v = tbl["resolution_scale"].value<int>()) {
      config.resolution_scale = *v;
      config.draw_resolution_scale_x = *v;
      config.draw_resolution_scale_y = *v;
    }
    if (auto v = tbl["d3d12_allow_variable_refresh_rate_and_tearing"].value<bool>()) {
      config.d3d12_allow_variable_refresh_rate_and_tearing = *v;
    }
    if (auto v = tbl["anisotropic_override"].value<int>()) config.anisotropic_override = *v;
    if (auto v = tbl["swap_post_effect"].value<std::string>()) config.swap_post_effect = *v;
    if (auto v = tbl["present_effect"].value<std::string>()) config.present_effect = *v;
    if (auto v = tbl["present_dither"].value<bool>()) config.present_dither = *v;
    if (auto v = tbl["show_fps_overlay"].value<bool>()) config.show_fps_overlay = *v;
    if (auto v = tbl["ultrawide_target_aspect"].value<double>()) config.ultrawide_target_aspect = *v;
    if (auto v = tbl["custom_game_root"].value<std::string>()) config.custom_game_root = *v;
    if (auto v = tbl["launcher_language"].value<std::string>()) config.launcher_language = *v;
    return true;
  } catch (const toml::parse_error&) {
    return false;
  }
}

bool ConfigManager::Save(const std::filesystem::path& toml_path, const GameConfig& config) {
  toml::table tbl;
  if (std::filesystem::exists(toml_path)) {
    try {
      tbl = toml::parse_file(toml_path.string());
    } catch (...) {
      tbl = toml::table{};
    }
  }

  tbl.insert_or_assign("gpu_plugin", config.gpu_plugin);
  tbl.insert_or_assign("d3d12_readback_resolve", config.d3d12_readback_resolve);
  tbl.insert_or_assign("skip_intro_videos", config.skip_intro_videos);
  tbl.insert_or_assign("log_verbose", config.log_verbose);
  tbl.insert_or_assign("log_level", config.log_level);
  tbl.insert_or_assign("protect_zero", config.protect_zero);
  tbl.insert_or_assign("input_backend", config.input_backend);
  tbl.insert_or_assign("mnk_mode", config.mnk_mode);
  tbl.insert_or_assign("fullscreen", config.fullscreen);
  tbl.insert_or_assign("vsync", config.vsync);
  tbl.insert_or_assign("d3d12_host_vsync", config.d3d12_host_vsync);
  tbl.insert_or_assign("video_mode_refresh_rate", config.video_mode_refresh_rate);
  tbl.insert_or_assign("resolution_scale", config.resolution_scale);
  tbl.insert_or_assign("draw_resolution_scale_x", config.resolution_scale);
  tbl.insert_or_assign("draw_resolution_scale_y", config.resolution_scale);
  tbl.insert_or_assign("d3d12_allow_variable_refresh_rate_and_tearing",
                       config.d3d12_allow_variable_refresh_rate_and_tearing);
  tbl.insert_or_assign("anisotropic_override", config.anisotropic_override);
  tbl.insert_or_assign("swap_post_effect", config.swap_post_effect);
  tbl.insert_or_assign("present_effect", config.present_effect);
  tbl.insert_or_assign("present_dither", config.present_dither);
  tbl.insert_or_assign("show_fps_overlay", config.show_fps_overlay);
  tbl.insert_or_assign("ultrawide_target_aspect", config.ultrawide_target_aspect);
  if (!config.custom_game_root.empty()) {
    tbl.insert_or_assign("custom_game_root", config.custom_game_root);
  } else {
    tbl.erase("custom_game_root");
  }
  tbl.insert_or_assign("launcher_language", config.launcher_language);

  std::ofstream out(toml_path, std::ios::trunc);
  if (!out.is_open()) return false;
  out << "# narutorise - runtime configuration generated by Naruto: Rise of a Ninja Launcher\n\n";
  out << tbl << "\n";
  out.flush();
  return out.good();
}
