#pragma once

#include <array>
#include <string>

enum class TextId {
  WindowTitle,
  AppTitle,
  AppSubtitle,
  TabPlay,
  TabSettings,
  TabGameFiles,
  GroupGraphics,
  GroupControls,
  DisplayLabel,
  AspectLabel,
  Aspect16x9,
  Aspect21x9,
  Aspect32x9,
  AspectTooltip,
  ResolutionLabel,
  Res1x,
  Res2x,
  Res3x,
  Res4x,
  RendererLabel,
  TextureFilteringLabel,
  AnisoDefault,
  AntiAliasingLabel,
  AaOff,
  AaFxaa,
  AaFxaaExtreme,
  PostProcessingLabel,
  PostBilinear,
  PostCas,
  PostFsr,
  DitherLabel,
  FpsOverlayLabel,
  FullscreenLabel,
  VsyncLabel,
  VsyncTooltip,
  SdlInputLabel,
  ControllerStatusLabel,
  NoControllerDetected,
  SkipIntroLabel,
  LanguageLabel,
  BtnPlay,
  BtnResetRecommended,
  BtnSaveSettings,
  BtnOpenFolder,
  SettingsAppliedNotice,
  SettingsSavedNotice,
  StatusReady,
  StatusNotFound,
  FilesFoundIn,
  FilesMissingDesc,
  FilesNotice,
  CurrentPathLabel,
  NoneDetected,
  BtnSelectFolder,
  BtnResetDefault,
  PathResetMsg,
  FooterNotice,
  LaunchSuccessMsg,
  LaunchFailedMsg,
  ExeNotFoundMsg,
  PathUpdatedMsg,
  PlayHeading,
  PlayIntro,
  ReadyDetail,
  ManageFiles,
  SettingsIntro,
  FilesIntro,
  FolderHeading,
  FolderHint,
  SetupHeading,
  SetupHint,
  RecommendedApplied,
  SaveFailed,
  ExeMissing,
  ExeMissingStatus,
  FilesDetected,
  Exit,
  // --- DLC / Content ---
  TabDlc,
  DlcHeading,
  DlcIntro,
  DlcInstalledHeading,
  DlcNoInstalled,
  DlcInstallLoose,
  DlcInstallLooseHint,
  DlcSelectLooseFolder,
  DlcInstallSuccess,
  DlcInstallFailed,
  DlcStfsStaged,
  DlcOpenContentFolder,
  DlcPrepareFolders,
  DlcFoldersReady,
  // --- Installer wizard ---
  InstWindowTitle,
  InstWelcomeTitle,
  InstWelcomeIntro,
  InstWelcomeStep1,
  InstWelcomeStep2,
  InstWelcomeStep3,
  InstWelcomeStep4,
  InstWelcomeStep5,
  InstWelcomeLegal,
  InstPayloadMissing,
  InstDestTitle,
  InstDestHint,
  InstBrowse,
  InstNext,
  InstBack,
  InstInstall,
  InstFinish,
  InstIsoTitle,
  InstIsoHint,
  InstIsoDialog,
  InstIsoChecking,
  InstIsoValid,
  InstIsoInvalid,
  InstIsoNoXex,
  InstIsoSkipCheck,
  InstIsoRequired,
  InstInvalidDest,
  InstProgressTitle,
  InstPreparing,
  InstRemovingOld,
  InstExtractingIso,
  InstCopyingFiles,
  InstWritingConfig,
  InstRegistering,
  InstComplete,
  InstCanceled,
  InstFailedTitle,
  InstFinishTitle,
  InstInstalledTo,
  InstGameFilesAt,
  InstShortcutDesktop,
  InstShortcutStartMenu,
  InstLaunchNow,
  // --- Uninstaller ---
  UnWindowTitle,
  UnIntro,
  UnKeepFiles,
  UnRemoveAll,
  UnCancel,
  UnDone,
  UnFailed,
  // --- Game language ---
  GroupGame,
  GameLanguageLabel,
  GameLanguageEnglish,
  GameLanguageFrench,
  GameLanguageGerman,
  GameLanguageSpanish,
  GameLanguageItalian,
  GameLanguageCustom,
  GameLanguageHint,
  LauncherLanguageTooltip,
  Count
};

class Localization {
 public:
  enum class Language {
    English,
    Portuguese,
    French,
    German,
    Spanish,
    Italian,
    Russian,
    Count
  };

  struct LanguageOption {
    Language language;
    const char* code;
    const char* name;
  };

  static const std::array<LanguageOption, 7>& GetLanguages();
  static void SetLanguage(Language lang);
  static Language GetLanguage();
  static void SetLanguageCode(const std::string& code);
  static std::string GetLanguageCode();
  static const char* Get(TextId id);
};

inline const char* Tr(TextId id) {
  return Localization::Get(id);
}
