#include "localization.h"

#include <array>

namespace {

Localization::Language g_current_language = Localization::Language::English;

// English string table (default)
const char* const kStringsEn[] = {
    "Naruto: Rise of a Ninja",
    "NARUTO: RISE OF A NINJA",
    "PC Recompilation Port (ReXGlue)",
    "PLAY",
    "SETTINGS",
    "GAME FILES",
    "Graphics Quality",
    "Controls",
    "Display:",
    "Aspect Ratio:",
    "16:9 - Standard (original)",
    "21:9 - UltraWide (3440x1440)",
    "32:9 - Super UltraWide (5120x1440)",
    "Dynamically adjusts 3D camera FOV horizontally without character stretching or distortion.",
    "Resolution:",
    "1280x720 - 1x (original)",
    "2560x1440 - 2x (recommended)",
    "3840x2160 - 3x (4K UHD)",
    "5120x2880 - 4x (5K UHD)",
    "Renderer:",
    "Texture Filtering:",
    "Default",
    "Anti-Aliasing:",
    "Off",
    "FXAA",
    "FXAA Extreme",
    "Post-Processing:",
    "Bilinear (default)",
    "CAS (sharpen)",
    "FSR EASU (upscale)",
    "Dithering",
    "FPS Overlay",
    "Fullscreen",
    "VSync (60 Hz lock)",
    "Keep enabled to maintain accurate game animation speeds and physics.",
    "Use SDL controller backend (Xbox / PlayStation controllers)",
    "Controller:",
    "No controller detected (Keyboard & Mouse)",
    "Skip intro videos (Ubisoft logos)",
    "Language:",
    "PLAY GAME",
    "Reset to Recommended",
    "Save Settings",
    "Open Game Folder",
    "Settings are applied when you click PLAY.",
    "Settings saved successfully.",
    "Game ready",
    "Game files not found",
    "Game files found in: %s",
    "To play, place your extracted Xbox 360 files inside 'game' or select an extracted folder in 'GAME FILES'. ISO extraction is available only in Setup.",
    "The game requires original Xbox 360 extracted files. Use Setup to extract your ISO, or copy the files into 'game'.",
    "Current Path: %s",
    "(None found)",
    "Select Extracted Game Folder...",
    "Reset to Default Path",
    "Path reset to default.",
    "Settings are saved when you play or close the launcher.",
    "Game launched successfully!",
    "Failed to start process: ",
    "Game executable not found at: ",
    "Path updated: ",
    "Your journey starts here.",
    "Return to the Hidden Leaf Village.",
    "Game files detected. You're ready to play.",
    "Manage game files",
    "Make the game feel at home on your PC.",
    "Connect your original game files to the PC port.",
    "Game folder",
    "Select the folder containing default.xex. Your original files are never moved or deleted.",
    "Have an ISO instead?",
    "Run Setup again to extract your original Xbox 360 ISO. ISO import is only available in the installer.",
    "Recommended settings applied.",
    "Could not save settings. Check folder write permissions.",
    "The PC game executable is missing. Reinstall the port using Setup.",
    "PC port not found",
    "Game files detected",
    "Exit launcher",
    // --- DLC / Content ---
    "DLC",
    "Downloadable Content",
    "Install DLC character packs for Naruto: Rise of a Ninja.",
    "Installed DLC",
    "No DLC installed yet.",
    "Install DLC Folder",
    "Select a folder with DLC files. Xbox 360 packages (.live/.con/.pirs) are installed automatically by the game on launch; already-extracted folders are copied directly.",
    "Select DLC folder...",
    "DLC installed successfully.",
    "Failed to install DLC:",
    "DLC package(s) staged. They will be installed automatically when you launch the game.",
    "Open DLC folder",
    "Prepare DLC folders",
    "DLC folder structure is ready.",
    // --- Installer wizard ---
    "Naruto: Rise of a Ninja - Setup",
    "Welcome to the Naruto: Rise of a Ninja PC Port installer",
    "This wizard installs the PC port and imports your original Xbox 360 game files.",
    "1. Choose the installation folder",
    "2. Select your Naruto: Rise of a Ninja ISO image",
    "3. The game files are extracted automatically",
    "4. Shortcuts are created (optional)",
    "5. Play through the launcher",
    "You must own the original game. No game files are distributed with this port.",
    "Installer payload not found. Run this installer from its distribution folder or use the generated Setup.",
    "Installation folder",
    "The port files will be copied to this folder.",
    "Browse...",
    "Next",
    "Back",
    "INSTALL",
    "Finish",
    "Game ISO image",
    "Select your original Xbox 360 ISO image (.iso).",
    "Select the Naruto: Rise of a Ninja ISO",
    "Checking ISO image...",
    "Valid Xbox 360 ISO: %u files (%.2f GB)",
    "The selected file is not a valid Xbox 360 ISO image.",
    "default.xex was not found in the ISO image.",
    "Skip extraction (game files already present in the destination)",
    "Select a valid ISO image or check 'Skip extraction' if the game files are already in place.",
    "Enter a valid installation folder.",
    "Installing",
    "Preparing installation...",
    "Removing previous game files...",
    "Extracting ISO image (this can take a few minutes)...",
    "Copying port files...",
    "Writing configuration...",
    "Registering in Add/Remove Programs...",
    "Installation complete!",
    "Installation canceled.",
    "Installation failed",
    "Installation complete",
    "Installed to: %s",
    "Game files at: %s",
    "Create Desktop shortcut",
    "Create Start Menu shortcut",
    "Run the Naruto launcher now",
    // --- Uninstaller ---
    "Naruto: Rise of a Ninja - Uninstall",
    "This removes the port files, the shortcuts and the Add/Remove Programs entry.",
    "Uninstall (keep game files)",
    "Uninstall everything",
    "Cancel",
    "Uninstall finished. Some files may remain until this window closes.",
    "Uninstall failed: %s",
};

// Portuguese string table (pt-BR)
const char* const kStringsPtBr[] = {
    "Naruto: Rise of a Ninja",
    "NARUTO: RISE OF A NINJA",
    "Port Recompilado de PC (ReXGlue)",
    "JOGAR",
    "CONFIGURAÇÕES",
    "ARQUIVOS",
    "Qualidade gráfica",
    "Controles",
    "Monitor:",
    "Proporção de tela:",
    "16:9 - Padrão (original)",
    "21:9 - UltraWide (3440x1440)",
    "32:9 - Super UltraWide (5120x1440)",
    "Ajusta dinamicamente o FOV da camera 3D horizontalmente sem esticar os personagens.",
    "Resolução:",
    "1280x720 - 1x (original)",
    "2560x1440 - 2x (recomendado)",
    "3840x2160 - 3x (4K UHD)",
    "5120x2880 - 4x (5K UHD)",
    "Renderizador:",
    "Filtro de texturas:",
    "Padrão",
    "Anti-Serrilhado:",
    "Desligado",
    "FXAA",
    "FXAA Extremo",
    "Pós-processamento:",
    "Bilinear (padrão)",
    "CAS (nitidez)",
    "FSR EASU (upscaling)",
    "Dithering",
    "Overlay de FPS",
    "Tela cheia",
    "VSync (Travar a 60 Hz)",
    "Manter ativado para garantir a velocidade correta das animacoes e fisica do jogo.",
    "Usar controles SDL (Xbox / PlayStation)",
    "Controle:",
    "Nenhum controle conectado",
    "Pular vídeos de abertura",
    "Idioma:",
    "JOGAR AGORA",
    "Usar recomendadas",
    "Salvar configurações",
    "Abrir Pasta do Jogo",
    "As alterações serão aplicadas ao iniciar o jogo.",
    "Configurações salvas com sucesso.",
    "Jogo pronto",
    "Arquivos do jogo não encontrados",
    "Arquivos do jogo localizados em: %s",
    "Selecione uma pasta extraída em ARQUIVOS ou coloque os dados em 'game'. Para importar uma ISO, use o instalador.",
    "O jogo necessita dos arquivos originais extraidos do Xbox 360. Use o instalador para extrair sua ISO ou copie os arquivos para 'game'.",
    "Pasta Atual: %s",
    "(Nenhuma encontrada)",
    "Selecionar pasta do jogo...",
    "Usar pasta padrão",
    "Caminho restaurado para o padrão.",
    "Configurações salvas ao iniciar ou fechar o launcher.",
    "Jogo iniciado com sucesso!",
    "Falha ao iniciar processo: ",
    "Executavel do jogo nao encontrado em: ",
    "Caminho atualizado: ",
    "Sua jornada começa aqui.",
    "Volte para a Vila Oculta da Folha.",
    "Arquivos do jogo detectados. Tudo pronto para jogar.",
    "Gerenciar arquivos do jogo",
    "Deixe o jogo do seu jeito no PC.",
    "Conecte os arquivos do seu jogo original ao port de PC.",
    "Pasta do jogo",
    "Selecione a pasta que contém default.xex. Seus arquivos originais nunca são movidos ou excluídos.",
    "Você tem uma ISO?",
    "Execute o instalador novamente para extrair sua ISO original de Xbox 360. A importação de ISO está disponível apenas no instalador.",
    "Configurações recomendadas aplicadas.",
    "Não foi possível salvar. Verifique a permissão de escrita na pasta.",
    "O executável de PC não foi encontrado. Reinstale o port pelo instalador.",
    "Port de PC não encontrado",
    "Arquivos do jogo detectados",
    "Fechar launcher",
    // --- DLC / Content ---
    "DLC",
    "Conteúdo Downloadable",
    "Instale pacotes de personagens DLC para Naruto: Rise of a Ninja.",
    "DLCs instalados",
    "Nenhum DLC instalado ainda.",
    "Instalar pasta de DLC",
    "Selecione uma pasta com arquivos de DLC. Pacotes do Xbox 360 (.live/.con/.pirs) sao instalados automaticamente pelo jogo ao iniciar; pastas ja extraidas sao copiadas diretamente.",
    "Selecionar pasta de DLC...",
    "DLC instalado com sucesso.",
    "Falha ao instalar DLC:",
    "Pacote(s) de DLC preparado(s). Serao instalados automaticamente quando voce iniciar o jogo.",
    "Abrir pasta de DLC",
    "Preparar pastas de DLC",
    "Estrutura de pastas de DLC pronta.",
    // --- Installer wizard ---
    "Naruto: Rise of a Ninja - Instalador",
    "Bem-vindo ao instalador do port de PC de Naruto: Rise of a Ninja",
    "Este assistente instala o port de PC e importa os arquivos originais do seu jogo de Xbox 360.",
    "1. Escolha a pasta de instalacao",
    "2. Selecione a imagem ISO de Naruto: Rise of a Ninja",
    "3. Os arquivos do jogo sao extraidos automaticamente",
    "4. Os atalhos sao criados (opcional)",
    "5. Jogue pelo launcher",
    "Voce deve possuir o jogo original. Nenhum arquivo do jogo e distribuido com este port.",
    "Payload do instalador nao encontrado. Execute este instalador pela pasta de distribuicao ou use o Setup gerado.",
    "Pasta de instalacao",
    "Os arquivos do port serao copiados para esta pasta.",
    "Procurar...",
    "Avancar",
    "Voltar",
    "INSTALAR",
    "Concluir",
    "Imagem ISO do jogo",
    "Selecione sua imagem ISO original de Xbox 360 (.iso).",
    "Selecione a ISO de Naruto: Rise of a Ninja",
    "Verificando imagem ISO...",
    "ISO de Xbox 360 valida: %u arquivos (%.2f GB)",
    "O arquivo selecionado nao e uma imagem ISO de Xbox 360 valida.",
    "O default.xex nao foi encontrado na imagem ISO.",
    "Pular extracao (arquivos do jogo ja presentes no destino)",
    "Selecione uma ISO valida ou marque 'Pular extracao' se os arquivos do jogo ja estao no lugar.",
    "Informe uma pasta de instalacao valida.",
    "Instalando",
    "Preparando a instalacao...",
    "Removendo arquivos anteriores do jogo...",
    "Extraindo a imagem ISO (isto pode levar alguns minutos)...",
    "Copiando arquivos do port...",
    "Gravando configuracao...",
    "Registrando em Adicionar ou Remover Programas...",
    "Instalacao concluida!",
    "Instalacao cancelada.",
    "Falha na instalacao",
    "Instalacao concluida",
    "Instalado em: %s",
    "Arquivos do jogo em: %s",
    "Criar atalho na Area de Trabalho",
    "Criar atalho no Menu Iniciar",
    "Executar o launcher do Naruto agora",
    // --- Uninstaller ---
    "Naruto: Rise of a Ninja - Desinstalador",
    "Isto remove os arquivos do port, os atalhos e o registro em Adicionar ou Remover Programas.",
    "Desinstalar (manter arquivos do jogo)",
    "Desinstalar tudo",
    "Cancelar",
    "Desinstalacao concluida. Alguns arquivos podem permanecer ate esta janela fechar.",
    "Falha na desinstalacao: %s",
};

static_assert(std::size(kStringsEn) == static_cast<size_t>(TextId::Count));
static_assert(std::size(kStringsPtBr) == static_cast<size_t>(TextId::Count));

}  // namespace

void Localization::SetLanguage(Localization::Language lang) {
  g_current_language = lang;
}

Localization::Language Localization::GetLanguage() {
  return g_current_language;
}

void Localization::SetLanguageCode(const std::string& code) {
  if (code == "pt_BR" || code == "pt-BR" || code == "pt") {
    g_current_language = Language::Portuguese;
  } else {
    g_current_language = Language::English;
  }
}

std::string Localization::GetLanguageCode() {
  return (g_current_language == Language::Portuguese) ? "pt_BR" : "en";
}

const char* Localization::Get(TextId id) {
  const size_t index = static_cast<size_t>(id);
  if (index >= static_cast<size_t>(TextId::Count)) {
    return "";
  }

  if (g_current_language == Language::Portuguese) {
    return kStringsPtBr[index];
  }
  return kStringsEn[index];
}
